### ISSUE TITLE
Crash bij reclamemomenten video

### ISSUE THREAD

**Issue by BasKiers** [Opvolger/plugin.video.rtlxl#1]
Ik heb momenteel Kodi v14.2 met versie 1.0.8 (al zegt Kodi v1.1.0) van deze plugin draaien met op een Raspberry Pi v1 model B+.

Bij het kijken van Expeditie Robinson crasht de raspberry-pi wanneer de video voorbij een reclamemoment komt. Ik heb dit niet bij meer video's geprobeerd maar is reproduceerbaar voor aflevering 10 van Expeditie Robinson.

**Comment by Opvolger** [comment]
Het probleem ligt bij de omxplayer met de pi en video formaat van rtl.

Als je bij de settings van video de omxplayer uitzet moet het wel goed gaan.
Op 8 nov. 2015 12:25 schreef "BasKiers" <notifications@github.com>:
